# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Board Game Exchange App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Board Game Exchange App
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'SwiftCSV'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
end
